---

- name: RunKibanaPB
  hosts: kibanavm
  become: yes
  tasks:

    - name: Run Kibana container
      docker_container:
        name: kibana01
        image: "huecker.io/library/kibana:8.2.2"
        state: started
        ports:
          - "5601:5601"
        env:
          SERVERNAME: "kibana"
          ELASTICSEARCH_HOSTS: "http://{{elastichost_ip}}:9200"
          xpack.security.enabled: "false"
          xpack.security.http.ssl.enabled: "false"
